import os
from datetime import datetime, timezone
from google.cloud import firestore

# 1. Connect to the database
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "google-keys.json"
db = firestore.Client()

# 2. Our Massive 60-Book Dummy Dataset
dummy_data = [
    # --- LORENZO'S LIBRARY (Sci-Fi, Dystopian, Tech) ---
    {"user": "lorenzo_test", "id": "b_dune", "title": "Dune", "author": "Frank Herbert",
     "genres": ["Sci-Fi", "Adventure"], "rating": 5},
    {"user": "lorenzo_test", "id": "b_found", "title": "Foundation", "author": "Isaac Asimov", "genres": ["Sci-Fi"],
     "rating": 4},
    {"user": "lorenzo_test", "id": "b_1984", "title": "1984", "author": "George Orwell",
     "genres": ["Dystopian", "Sci-Fi"], "rating": 5},
    {"user": "lorenzo_test", "id": "b_neuro", "title": "Neuromancer", "author": "William Gibson",
     "genres": ["Sci-Fi", "Cyberpunk"], "rating": 5},
    {"user": "lorenzo_test", "id": "b_martian", "title": "The Martian", "author": "Andy Weir",
     "genres": ["Sci-Fi", "Adventure"], "rating": 4},
    {"user": "lorenzo_test", "id": "b_hail", "title": "Project Hail Mary", "author": "Andy Weir", "genres": ["Sci-Fi"],
     "rating": 5},
    {"user": "lorenzo_test", "id": "b_brave", "title": "Brave New World", "author": "Aldous Huxley",
     "genres": ["Dystopian", "Classic"], "rating": 4},
    {"user": "lorenzo_test", "id": "b_fah", "title": "Fahrenheit 451", "author": "Ray Bradbury",
     "genres": ["Dystopian", "Sci-Fi"], "rating": 4},
    {"user": "lorenzo_test", "id": "b_robot", "title": "I, Robot", "author": "Isaac Asimov", "genres": ["Sci-Fi"],
     "rating": 4},
    {"user": "lorenzo_test", "id": "b_androids", "title": "Do Androids Dream of Electric Sheep?",
     "author": "Philip K. Dick", "genres": ["Sci-Fi", "Cyberpunk"], "rating": 5},
    {"user": "lorenzo_test", "id": "b_ender", "title": "Ender's Game", "author": "Orson Scott Card",
     "genres": ["Sci-Fi", "Action"], "rating": 5},
    {"user": "lorenzo_test", "id": "b_time", "title": "The Time Machine", "author": "H.G. Wells",
     "genres": ["Sci-Fi", "Classic"], "rating": 3},
    {"user": "lorenzo_test", "id": "b_carbon", "title": "Altered Carbon", "author": "Richard K. Morgan",
     "genres": ["Sci-Fi", "Cyberpunk"], "rating": 4},
    {"user": "lorenzo_test", "id": "b_expanse", "title": "Leviathan Wakes", "author": "James S.A. Corey",
     "genres": ["Sci-Fi", "Space Opera"], "rating": 5},
    {"user": "lorenzo_test", "id": "b_dark", "title": "Dark Matter", "author": "Blake Crouch",
     "genres": ["Sci-Fi", "Thriller"], "rating": 4},
    {"user": "lorenzo_test", "id": "b_recur", "title": "Recursion", "author": "Blake Crouch",
     "genres": ["Sci-Fi", "Thriller"], "rating": 5},
    {"user": "lorenzo_test", "id": "b_ready", "title": "Ready Player One", "author": "Ernest Cline",
     "genres": ["Sci-Fi", "Adventure"], "rating": 4},
    {"user": "lorenzo_test", "id": "b_jurassic", "title": "Jurassic Park", "author": "Michael Crichton",
     "genres": ["Sci-Fi", "Thriller"], "rating": 5},
    {"user": "lorenzo_test", "id": "b_hyperion", "title": "Hyperion", "author": "Dan Simmons",
     "genres": ["Sci-Fi", "Space Opera"], "rating": 5},
    {"user": "lorenzo_test", "id": "b_hobbit", "title": "The Hobbit", "author": "J.R.R. Tolkien",
     "genres": ["Fantasy", "Adventure"], "rating": 4},

    # --- PIETRO'S LIBRARY (Thriller, Mystery, Horror) ---
    {"user": "pietro_test", "id": "b_silent", "title": "The Silent Patient", "author": "Alex Michaelides",
     "genres": ["Thriller", "Mystery"], "rating": 5},
    {"user": "pietro_test", "id": "b_gone", "title": "Gone Girl", "author": "Gillian Flynn",
     "genres": ["Thriller", "Mystery"], "rating": 5},
    {"user": "pietro_test", "id": "b_dragon", "title": "The Girl with the Dragon Tattoo", "author": "Stieg Larsson",
     "genres": ["Crime", "Thriller"], "rating": 4},
    {"user": "pietro_test", "id": "b_shutter", "title": "Shutter Island", "author": "Dennis Lehane",
     "genres": ["Thriller", "Mystery"], "rating": 5},
    {"user": "pietro_test", "id": "b_shining", "title": "The Shining", "author": "Stephen King",
     "genres": ["Horror", "Thriller"], "rating": 5},
    {"user": "pietro_test", "id": "b_it", "title": "It", "author": "Stephen King",
     "genres": ["Horror", "Coming-of-age"], "rating": 4},
    {"user": "pietro_test", "id": "b_misery", "title": "Misery", "author": "Stephen King",
     "genres": ["Horror", "Thriller"], "rating": 5},
    {"user": "pietro_test", "id": "b_davinci", "title": "The Da Vinci Code", "author": "Dan Brown",
     "genres": ["Thriller", "Mystery"], "rating": 4},
    {"user": "pietro_test", "id": "b_angels", "title": "Angels & Demons", "author": "Dan Brown",
     "genres": ["Thriller", "Mystery"], "rating": 3},
    {"user": "pietro_test", "id": "b_silence", "title": "The Silence of the Lambs", "author": "Thomas Harris",
     "genres": ["Thriller", "Crime"], "rating": 5},
    {"user": "pietro_test", "id": "b_psycho", "title": "Psycho", "author": "Robert Bloch",
     "genres": ["Horror", "Thriller"], "rating": 4},
    {"user": "pietro_test", "id": "b_snowman", "title": "The Snowman", "author": "Jo Nesbø",
     "genres": ["Crime", "Thriller"], "rating": 4},
    {"user": "pietro_test", "id": "b_train", "title": "The Girl on the Train", "author": "Paula Hawkins",
     "genres": ["Thriller", "Mystery"], "rating": 4},
    {"user": "pietro_test", "id": "b_sharp", "title": "Sharp Objects", "author": "Gillian Flynn",
     "genres": ["Thriller", "Crime"], "rating": 4},
    {"user": "pietro_test", "id": "b_darkplaces", "title": "Dark Places", "author": "Gillian Flynn",
     "genres": ["Thriller", "Mystery"], "rating": 4},
    {"user": "pietro_test", "id": "b_alienist", "title": "The Alienist", "author": "Caleb Carr",
     "genres": ["Crime", "Historical"], "rating": 4},
    {"user": "pietro_test", "id": "b_cold", "title": "In Cold Blood", "author": "Truman Capote",
     "genres": ["True Crime", "Classic"], "rating": 5},
    {"user": "pietro_test", "id": "b_none", "title": "And Then There Were None", "author": "Agatha Christie",
     "genres": ["Mystery", "Crime"], "rating": 5},
    {"user": "pietro_test", "id": "b_orient", "title": "Murder on the Orient Express", "author": "Agatha Christie",
     "genres": ["Mystery", "Crime"], "rating": 5},
    {"user": "pietro_test", "id": "b_dune", "title": "Dune", "author": "Frank Herbert",
     "genres": ["Sci-Fi", "Adventure"], "rating": 3},

    # --- CELIA'S LIBRARY (Fantasy, Romance, Classics) ---
    {"user": "celia_test", "id": "b_pride", "title": "Pride and Prejudice", "author": "Jane Austen",
     "genres": ["Romance", "Classic"], "rating": 5},
    {"user": "celia_test", "id": "b_lotr", "title": "The Lord of the Rings", "author": "J.R.R. Tolkien",
     "genres": ["Fantasy", "Adventure"], "rating": 5},
    {"user": "celia_test", "id": "b_hobbit", "title": "The Hobbit", "author": "J.R.R. Tolkien",
     "genres": ["Fantasy", "Adventure"], "rating": 5},
    {"user": "celia_test", "id": "b_hp1", "title": "Harry Potter and the Sorcerer's Stone", "author": "J.K. Rowling",
     "genres": ["Fantasy", "Young Adult"], "rating": 5},
    {"user": "celia_test", "id": "b_hp2", "title": "Harry Potter and the Chamber of Secrets", "author": "J.K. Rowling",
     "genres": ["Fantasy", "Young Adult"], "rating": 4},
    {"user": "celia_test", "id": "b_hp3", "title": "Harry Potter and the Prisoner of Azkaban", "author": "J.K. Rowling",
     "genres": ["Fantasy", "Young Adult"], "rating": 5},
    {"user": "celia_test", "id": "b_got", "title": "A Game of Thrones", "author": "George R.R. Martin",
     "genres": ["Fantasy", "Epic"], "rating": 5},
    {"user": "celia_test", "id": "b_name", "title": "The Name of the Wind", "author": "Patrick Rothfuss",
     "genres": ["Fantasy", "Adventure"], "rating": 5},
    {"user": "celia_test", "id": "b_mistborn", "title": "Mistborn: The Final Empire", "author": "Brandon Sanderson",
     "genres": ["Fantasy", "Action"], "rating": 4},
    {"user": "celia_test", "id": "b_jane", "title": "Jane Eyre", "author": "Charlotte Brontë",
     "genres": ["Romance", "Classic"], "rating": 5},
    {"user": "celia_test", "id": "b_wuthering", "title": "Wuthering Heights", "author": "Emily Brontë",
     "genres": ["Romance", "Classic"], "rating": 4},
    {"user": "celia_test", "id": "b_little", "title": "Little Women", "author": "Louisa May Alcott",
     "genres": ["Classic", "Coming-of-age"], "rating": 5},
    {"user": "celia_test", "id": "b_sense", "title": "Sense and Sensibility", "author": "Jane Austen",
     "genres": ["Romance", "Classic"], "rating": 4},
    {"user": "celia_test", "id": "b_emma", "title": "Emma", "author": "Jane Austen", "genres": ["Romance", "Classic"],
     "rating": 4},
    {"user": "celia_test", "id": "b_outlander", "title": "Outlander", "author": "Diana Gabaldon",
     "genres": ["Romance", "Historical Fiction"], "rating": 5},
    {"user": "celia_test", "id": "b_narnia", "title": "The Lion, the Witch and the Wardrobe", "author": "C.S. Lewis",
     "genres": ["Fantasy", "Classic"], "rating": 4},
    {"user": "celia_test", "id": "b_alice", "title": "Alice's Adventures in Wonderland", "author": "Lewis Carroll",
     "genres": ["Fantasy", "Classic"], "rating": 4},
    {"user": "celia_test", "id": "b_peter", "title": "Peter Pan", "author": "J.M. Barrie",
     "genres": ["Fantasy", "Classic"], "rating": 4},
    {"user": "celia_test", "id": "b_gatsby", "title": "The Great Gatsby", "author": "F. Scott Fitzgerald",
     "genres": ["Classic", "Fiction"], "rating": 5},
    {"user": "celia_test", "id": "b_1984", "title": "1984", "author": "George Orwell",
     "genres": ["Dystopian", "Sci-Fi"], "rating": 4},
]

print(f"Starting database population with {len(dummy_data)} books...")

# 3. Loop through and save everything
for count, data in enumerate(dummy_data, 1):
    doc_ref = db.collection("users").document(data["user"]).collection("library").document(data["id"])

    doc_ref.set({
        "title": data["title"],
        "author": data["author"],
        "genres": data["genres"],
        "rating": data["rating"],
        "status": "read",
        "added_at": datetime.now(timezone.utc)
    })
    print(f"[{count}/60] Added '{data['title']}' to {data['user']}'s library")

print("Database successfully populated! You are ready to test.")